from tkinterimport*
#from tkinterimportttk
importtkinter.fontasfont
importtkinter.messageboxasMessageBox
importmysql.connectorasmysql
definsert():
Aadharid=e_Aadharid.get()
username=e_username.get();
passw=e_passw.get();
if(Aadharid==""orusername==""orpassw==""):
MessageBox.showinfo("InsertStatus","AllFieldsarerequired")
else:
con=
mysql.connect(host="localhost",user="root",password="priya@1992002",database="PERS
ONALINFORMATION")
cursor=con.cursor()
cursor.execute("insertintologinvalues('"+Aadharid+"','"+username+"','"+
passw+"')")
cursor.execute("commit");
e_Aadharid.delete(0,'end')
e_username.delete(0,'end')
e_passw.delete(0,'end')
show()
MessageBox.showinfo("InsertStatus","InsertedSuccessfully");
con.close();
defdelete():
if(e_Aadharid.get()==""):
MessageBox.showinfo("DeleteStatus","IDiscompulsaryfordelete")
else:
con=
mysql.connect(host="localhost",user="root",password="priya@1992002",database="PERS
ONALINFORMATION")
cursor=con.cursor()
cursor.execute("deletefrom loginwhereAadharid='"+e_Aadharid.get()+"'")
cursor.execute("commit");
e_Aadharid.delete(0,'end')
e_username.delete(0,'end')
e_passw.delete(0,'end')
MessageBox.showinfo("DeleteStatus","DeletedSuccessfully");
show()
con.close();
defupdate():
Aadharid=e_Aadharid.get()
username=e_username.get();
passw=e_passw.get();
if(Aadharid==""orusername==""orpassw==""):
MessageBox.showinfo("UpdateStatus","AllFieldsarerequired")
else:
con=
mysql.connect(host="localhost",user="root",password="priya@1992002",database="PERS
ONALINFORMATION")
cursor=con.cursor()
cursor.execute("updateloginsetusername='"+username+"',passw='"+passw
+"'whereAadharid='"+Aadharid+"'")
cursor.execute("commit");
e_Aadharid.delete(0,'end')
e_username.delete(0,'end')
e_passw.delete(0,'end')
show()
MessageBox.showinfo("UpdateStatus","UpdatetedSuccessfully");
con.close();
defget():
if(e_Aadharid.get()==""):
MessageBox.showinfo("FetchStatus","IDiscompulsaryfordelete")
else:
con=
mysql.connect(host="localhost",user="root",password="priya@1992002",database="PERS
ONALINFORMATION")
cursor=con.cursor()
cursor.execute("select*from loginwhereAadharid='"+e_Aadharid.get()+"'")
rows=cursor.fetchall()
forrowinrows:
e_username.insert(0,row[1])
e_passw.insert(0,row[2])
con.close();
defnextstep():
Aadharid=e_Aadharid.get()
username=e_username.get();
passw=e_passw.get();
if(Aadharid==""orusername==""orpassw==""):
MessageBox.showinfo("NEXT","COULDYOUWANTTOCONTINUE")
else:
con=mysql.connect(host="localhost",user="root",password="priya@1992002",database="
PERSONALINFORMATION")
cursor=con.cursor()
cursor.execute("commit");
e_Aadharid.delete(0,'end')
e_username.delete(0,'end')
e_passw.delete(0,'end')
MessageBox.showinfo("YOURFILESORRECORDED")
con.close();
root.destroy()
return
defshow():
con=
mysql.connect(host="localhost",user="root",password="priya@1992002",database="PERS
ONALINFORMATION")
cursor=con.cursor()
cursor.execute("select*from login")
rows=cursor.fetchall()
list.delete(0,list.size())
forrowinrows:
insertData=str(row[0])+' '+row[1]
list.insert(list.size()+1,insertData)
con.close();
root=Tk()
root.geometry("500x400");
root.title("MINIPROJECT");
bg=PhotoImage(file="C:/Users/ELCOT/Pictures/Screenshots/IMG_20211021_153445.
png")
insert=Label(root,image=bg)
insert.place(x=0,y=0)
Aadharid=Label(root,text='AADHARID',bg='#091e42',fg='white')
Aadharid.place(x=20,y=30);
username=Label(root,text='NAME',bg='#091e42',fg='white')
username.place(x=20,y=60);
passw=Label(root,text='PASSWORD',bg='#091e42',fg='white')
passw.place(x=20,y=90);
e_Aadharid=Entry(width=20,bd=5)
e_Aadharid.place(x=150,y=30)
e_username=Entry(width=20,bd=5)
e_username.place(x=150,y=60)
e_passw=Entry(width=20,show="*",bd=5)
e_passw.place(x=150,y=90)
insert=Button(root,text="LOGIN",
bg='#091e42',fg='white',width=5,bd=5,command=insert)
insert.place(x=20,y=140)
delete
=Button(root,text="DELETE",bg='#091e42',fg='white',width=5,bd=5,command=delete)
delete.place(x=70,y=140)
update
=Button(root,text="UPDATE",bg='#091e42',fg='white',width=5,bd=5,command=update)
update.place(x=130,y=140)
get=Button(root,text="GET",bg='#091e42',fg='white',width=5,bd=5,command=get)
get.place(x=190,y=140)
next=Button(root,text="NEXT",bg='#091e42',fg='white',width=5,bd=5,command=next
step)
next.place(x=250,y=140)
list=Listbox(root)
list.place(x=350,y=30)
show()
root.mainloop()
##############################################################
###################################FORM1

newwindow=Tk()
newwindow.title("personalinformation")
newwindow.geometry("700x650")
bg=PhotoImage(file="C:/Users/ELCOT/Pictures/Screenshots/IMG_20211021_153407.p
ng")
insert=Label(newwindow,image=bg)
insert.place(x=0,y=0)
lbl=Label(newwindow,text="***BIODATA***",font=('white',12,'italic
bold'),borderwidth=4,width=25,relief=GROOVE,bg='#116562')
lbl.pack()
Aadharid=Label(newwindow,text="AADHARID",bg='#091e42',fg='white')
Aadharid.place(x=30,y=40)
name=Label(newwindow,text="NAME",bg='#091e42',fg='white')
name.place(x=30,y=80)
age=Label(newwindow,text="AGE",bg='#091e42',fg='white')
age.place(x=30,y=120)
gender=Label(newwindow,text="GENDER",bg='#091e42',fg='white')
gender.place(x=30,y=160)
nationality=Label(newwindow,text="NATIONALITY",bg='#091e42',fg='white')
nationality.place(x=30,y=200)
mobileno=Label(newwindow,text="MOBILENUMBER",bg='#091e42',fg='white')
mobileno.place(x=30,y=240)
doorno=Label(newwindow,text="DOORNUMBER",bg='#091e42',fg='white')
doorno.place(x=30,y=280)
streetname=Label(newwindow,text="STREETNAME",bg='#091e42',fg='white')
streetname.place(x=30,y=320)
area=Label(newwindow,text="AREA",bg='#091e42',fg='white')
area.place(x=30,y=360)
city=Label(newwindow,text="CITY",bg='#091e42',fg='white')
city.place(x=30,y=400)
state=Label(newwindow,text="STATE",bg='#091e42',fg='white')
state.place(x=30,y=440)
dob=Label(newwindow,text="DATEOFBIRTH",bg='#091e42',fg='white')
dob.place(x=30,y=480)
e_Aadharid=Entry(width=30,bd=5)
e_Aadharid.place(x=200,y=40)
e_name=Entry(width=30,bd=5)
e_name.place(x=200,y=80)
e_age=Entry(width=30,bd=5)
e_age.place(x=200,y=120)
e_gender=Entry(width=30,bd=5)
e_gender.place(x=200,y=160)
e_nationality=Entry(width=30,bd=5)
e_nationality.place(x=200,y=200)
e_mobileno=Entry(width=30,bd=5)
e_mobileno.place(x=200,y=240)
e_doorno=Entry(width=30,bd=5)
e_doorno.place(x=200,y=280)
e_streetname=Entry(width=30,bd=5)
e_streetname.place(x=200,y=320)
e_area=Entry(width=30,bd=5)
e_area.place(x=200,y=360)
e_city=Entry(width=30,bd=5)
e_city.place(x=200,y=400)
e_state=Entry(width=30,bd=5)
e_state.place(x=200,y=440)
e_dob=Entry(width=30,bd=5)
e_dob.place(x=200,y=480)
definsert():
Aadharid=e_Aadharid.get();
name=e_name.get();
age=e_age.get();
gender=e_gender.get();
nationality=e_nationality.get();
mobileno=e_mobileno.get();
doorno=e_doorno.get();
streetname=e_streetname.get();
area=e_area.get();
city=e_city.get();
state=e_state.get();
dob=e_dob.get();
if(Aadharid==""orname==""orage==""orgender==""ornationality==""or
mobileno==""ordoorno==""orstreetname==""orarea==""orcity==""orstate==""or
dob==""):
MessageBox.showinfo("INSERTSTATUS","ALLFIELDSAREREQUIRED")
else:
con=mysql.connect(host="localhost",user="root",password="priya@1992002",database="PERSONALINFORMATION")
cursor=con.cursor()
cursor.execute("insertintobiod
values('"+Aadharid+"','"+name+"','"+age+"','"+gender+"','"+nationality+"','"+mobileno+"','"
+doorno+"','"+streetname+"','"+area+"','"+city+"','"+state+"','"+dob+"')")
cursor.execute("commit");
e_Aadharid.delete(0,'end')
e_name.delete(0,'end')
e_age.delete(0,'end')
e_gender.delete(0,'end')
e_nationality.delete(0,'end')
e_mobileno.delete(0,'end')
e_doorno.delete(0,'end')
e_streetname.delete(0,'end')
e_area.delete(0,'end')
e_city.delete(0,'end')
e_state.delete(0,'end')
e_dob.delete(0,'end')
MessageBox.showinfo("INSERTSTATUS","INSERTEDSUCCESSFULLY");
con.close();
defupdate2():
Aadharid=e_Aadharid.get()
name=e_name.get();
age=e_age.get();
gender=e_gender.get();
nationality=e_nationality.get();mobileno=e_mobileno.get();
doorno=e_doorno.get();
streetname=e_streetname.get();
area=e_area.get();
city=e_city.get();
state=e_state.get();
dob=e_dob.get();
if(Aadharid==""orname==""orage==""orgender==""ornationality==""or
mobileno==""ordoorno==""orstreetname==""orarea==""orcity==""orstate==""or
dob==""):
MessageBox.showinfo("UpdateStatus","AllFieldsarerequired")
else:
con=
mysql.connect(host="localhost",user="root",password="priya@1992002",database="PERS
ONALINFORMATION")
cursor=con.cursor()
cursor.execute("updatebiodsetname='"+name+"',age='"+age+"',gender='"+
gender+"',nationality='"+nationality+"',mobileno='"+mobileno+"',doorno='"+doorno
+"',streetname='"+streetname+"',area='"+area+"',city='"+city+"',state='"+state
+"',dob='"+dob+"'whereAadharid='"+Aadharid+"'")
cursor.execute("commit");
e_Aadharid.delete(0,'end')
e_name.delete(0,'end')
e_age.delete(0,'end')
e_gender.delete(0,'end')
e_nationality.delete(0,'end')
e_mobileno.delete(0,'end')e_doorno.delete(0,'end')
e_streetname.delete(0,'end')
e_area.delete(0,'end')
e_city.delete(0,'end')
e_state.delete(0,'end')
e_dob.delete(0,'end')
MessageBox.showinfo("UpdateStatus","UpdatedSuccessfully");
con.close();
defget2():
if(e_Aadharid.get()==""):
MessageBox.showinfo("FetchStatus","IDiscompulsaryfordelete")
else:
con=
mysql.connect(host="localhost",user="root",password="priya@1992002",database="PERS
ONALINFORMATION")
cursor=con.cursor()
cursor.execute("select*from biodwhereAadharid='"+e_Aadharid.get()+"'")
rows=cursor.fetchall()
forrowinrows:
e_name.insert(0,row[1])
e_age.insert(0,row[2])
e_gender.insert(0,row[3])
e_nationality.insert(0,row[4])
e_mobileno.insert(0,row[5])e_doorno.insert(0,row[6])
e_streetname.insert(0,row[7])
e_area.insert(0,row[8])
e_city.insert(0,row[9])
e_state.insert(0,row[10])
e_dob.insert(0,row[11])
con.close();
defnextone():
Aadharid=e_Aadharid.get();
name=e_name.get();
age=e_age.get();
gender=e_gender.get();
nationality=e_nationality.get();
mobileno=e_mobileno.get();
doorno=e_doorno.get();
streetname=e_streetname.get();
area=e_area.get();
city=e_city.get();
state=e_state.get();
dob=e_dob.get();
if(Aadharid==""orname==""orage==""orgender==""ornationality==""or
mobileno==""ordoorno==""orstreetname==""orarea==""orcity==""orstate==""or
dob==""):
MessageBox.showinfo("NEXT","COULD YOU WANT TO CONTINUE")
con=mysql.connect(host="localhost",user="root",password="priya@1992002",database="
PERSONALINFORMATION")
cursor=con.cursor()
cursor.execute("commit");
e_Aadharid.delete(0,'end')
e_name.delete(0,'end')
e_age.delete(0,'end')
e_gender.delete(0,'end')
e_nationality.delete(0,'end')
e_mobileno.delete(0,'end')
e_doorno.delete(0,'end')
e_streetname.delete(0,'end')
e_area.delete(0,'end')
e_city.delete(0,'end')
e_state.delete(0,'end')
e_dob.delete(0,'end')
MessageBox.showinfo("NEXT","COULDYOUWANTTOCONTINUE");
con.close();
newwindow.destroy()
return
insert=Button(newwindow,text="INSERT",bg='#116562',fg='white',width=7,bd=5,com
mand=insert)
insert.place(x=100,y=540)update2=Button(newwindow,text="UPDATE",bg='#116562',fg='white',width=7,bd=5,c
ommand=update2)
update2.place(x=170,y=540)
get2=Button(newwindow,text="GETDATA",bg='#116562',fg='white',width=7,bd=5,co
mmand=get2)
get2.place(x=250,y=540)
nextone=Button(newwindow,text="NEXT",bg='#116562',fg='white',width=7,bd=5,com
mand=nextone)
nextone.place(x=320,y=540)
newwindow.mainloop()
##############################################################
####FORM 3
#form2
newwindow2=Tk()
newwindow2.title("personalinformation")
newwindow2.geometry("750x650")
bg=PhotoImage(file="C:/Users/ELCOT/Pictures/Screenshots/IMG_20211021_153427
(1).png")
insert=Label(newwindow2,image=bg)
insert.place(x=0,y=0)
lbl=Label(newwindow2,text="******BASICDETAILS******",font=('white',12,'italic
bold'),borderwidth=4,width=25,relief=GROOVE,bg='#116562')
lbl.pack()Aadharid=Label(newwindow2,text="AADHARID",bg='#091e42',fg='white')
Aadharid.place(x=30,y=40)
fathername=Label(newwindow2,text="FATHERNAME",bg='#091e42',fg='white')
fathername.place(x=30,y=80)
mothername=Label(newwindow2,text="MOTHERNAME",bg='#091e42',fg='white')
mothername.place(x=30,y=120)
accno=Label(newwindow2,text="ACCOUNTNUMBER",bg='#091e42',fg='white')
accno.place(x=30,y=160)
bankname=Label(newwindow2,text="BANKNAME",bg='#091e42',fg='white')
bankname.place(x=30,y=200)
IFSC=Label(newwindow2,text="IFSCCODE",bg='#091e42',fg='white')
IFSC.place(x=30,y=240)
creditno=Label(newwindow2,text="CREDITCARDNUMBER",bg='#091e42',fg='white')
creditno.place(x=30,y=280)
debitno=Label(newwindow2,text="DEBITCARDNUMBER",bg='#091e42',fg='white')
debitno.place(x=30,y=320)
tenthmark=Label(newwindow2,text="TENTHMARKSHEET",bg='#091e42',fg='white')
tenthmark.place(x=30,y=360)
twenthmark=Label(newwindow2,text="TWENTH
MARKSHEET",bg='#091e42',fg='white')
twenthmark.place(x=30,y=400)
cgpa=Label(newwindow2,text="CGPA",bg='#091e42',fg='white')
cgpa.place(x=30,y=440)
e_Aadharid=Entry(width=30,bd=5)
e_Aadharid.place(x=200,y=40)
e_fathername=Entry(width=30,bd=5)
e_fathername.place(x=200,y=80)
e_mothername=Entry(width=30,bd=5)
e_mothername.place(x=200,y=120)
e_accno=Entry(width=30,bd=5)
e_accno.place(x=200,y=160)
e_bankname=Entry(width=30,bd=5)
e_bankname.place(x=200,y=200)
e_IFSC=Entry(width=30,bd=5)
e_IFSC.place(x=200,y=240)
e_creditno=Entry(width=30,bd=5)
e_creditno.place(x=200,y=280)
e_debitno=Entry(width=30,bd=5)
e_debitno.place(x=200,y=320)
e_tenthmark=Entry(width=30,bd=5)
e_tenthmark.place(x=200,y=360)
e_twenthmark=Entry(width=30,bd=5)
e_twenthmark.place(x=200,y=400)
e_cgpa=Entry(width=30,bd=5)
e_cgpa.place(x=200,y=440)
definsert():
Aadharid=e_Aadharid.get();
fathername=e_fathername.get();
mothername=e_mothername.get();
accno=e_accno.get();
bankname=e_bankname.get();
IFSC=e_IFSC.get();
creditno=e_creditno.get();
debitno=e_debitno.get();
tenthmark=e_tenthmark.get();
twenthmark=e_twenthmark.get();
cgpa=e_cgpa.get();
if(Aadharid==""orfathername==""ormothername==""oraccno==""or
bankname==""orIFSC==""orcreditno==""ordebitno==""ortenthmark==""or
twenthmark==""orcgpa==""):
MessageBox.showinfo("INSERTSTATUS","ALLFIELDSAREREQUIRED")
else:
con=mysql.connect(host="localhost",user="root",password="priya@1992002",database="
PERSONALINFORMATION")
cursor=con.cursor()
cursor.execute("insertintoedubank
values('"+Aadharid+"','"+fathername+"','"+mothername+"','"+accno+"','"+bankname+"','"+
IFSC+"','"+creditno+"','"+debitno+"','"+tenthmark+"','"+twenthmark+"','"+cgpa+"')")
cursor.execute("commit");
e_Aadharid.delete(0,'end')
e_fathername.delete(0,'end')
e_mothername.delete(0,'end')
e_accno.delete(0,'end')
e_bankname.delete(0,'end')
e_IFSC.delete(0,'end')
e_creditno.delete(0,'end')
e_debitno.delete(0,'end')
e_tenthmark.delete(0,'end')
e_twenthmark.delete(0,'end')
e_cgpa.delete(0,'end')
MessageBox.showinfo("INSERTSTATUS","INSERTEDSUCCESSFULLY");
con.close();
defupdate3():
Aadharid=e_Aadharid.get()
fathername=e_fathername.get();
mothername=e_mothername.get();
accno=e_accno.get();
bankname=e_bankname.get();
IFSC=e_IFSC.get();
creditno=e_creditno.get();
debitno=e_debitno.get();
tenthmark=e_tenthmark.get();
twenthmark=e_twenthmark.get();
cgpa=e_cgpa.get();
if(Aadharid==""orfathername==""ormothername==""oraccno==""or
bankname==""orIFSC==""orcreditno==""ordebitno==""ortenthmark==""or
twenthmark==""orcgpa==""):
MessageBox.showinfo("UpdateStatus","AllFieldsarerequired")
else:
con=
mysql.connect(host="localhost",user="root",password="priya@1992002",database="PERS
ONALINFORMATION")
cursor=con.cursor()
cursor.execute("updateedubanksetfathername='"+fathername+"',
mothername='"+mothername+"',accno='"+accno+"',bankname='"+bankname
+"',IFSC='"+IFSC+"',creditno='"+creditno+"',debitno='"+debitno+"',tenthmark='"+
tenthmark+"',twenthmark='"+twenthmark+"',cpga='"+cgpa+"'whereAadharid='"+
Aadharid+"'")
cursor.execute("commit");
e_Aadharid.delete(0,'end')
e_fathername.delete(0,'end')
e_mothername.delete(0,'end')
e_accno.delete(0,'end')
e_bankname.delete(0,'end')
e_IFSC.delete(0,'end')
e_creditno.delete(0,'end')
e_debitno.delete(0,'end')
e_tenthmark.delete(0,'end')
e_twenthmark.delete(0,'end')
e_cgpa.delete(0,'end')
MessageBox.showinfo("UpdateStatus","UpdatedSuccessfully");
con.close();
defget3():
if(e_Aadharid.get()==""):
MessageBox.showinfo("FetchStatus","IDiscompulsaryfordelete")
else:
con=
mysql.connect(host="localhost",user="root",password="priya@1992002",database="PERS
ONALINFORMATION")
cursor=con.cursor()
cursor.execute("select*from edubankwhereAadharid='"+e_Aadharid.get()+"'")
rows=cursor.fetchall()
forrowinrows:
e_fathername.insert(0,row[1])
e_mothername.insert(0,row[2])
e_accno.insert(0,row[3])
e_bankname.insert(0,row[4])
e_IFSC.insert(0,row[5])
e_creditno.insert(0,row[6])
e_debitno.insert(0,row[7])
e_tenthmark.insert(0,row[8])
e_twenthmark.insert(0,row[9])
e_cgpa.insert(0,row[10])
con.close();
defnexttwo():
Aadharid=e_Aadharid.get();
fathername=e_fathername.get();
mothername=e_mothername.get();
accno=e_accno.get();
bankname=e_bankname.get();
IFSC=e_IFSC.get();
creditno=e_creditno.get();
debitno=e_debitno.get();
tenthmark=e_tenthmark.get();
twenthmark=e_twenthmark.get();
cgpa=e_cgpa.get();
if(Aadharid==""orfathername==""ormothername==""oraccno==""or
bankname==""orIFSC==""orcreditno==""ordebitno==""ortenthmark==""or
twenthmark==""orcgpa==""):
MessageBox.showinfo("NEXT","COULDYOUWANTTOCONTINUE");
else:
con=mysql.connect(host="localhost",user="root",password="priya@1992002",database="
PERSONALINFORMATION")
cursor=con.cursor()
cursor.execute("commit");
e_Aadharid.delete(0,'end')
e_fathername.delete(0,'end')
e_mothername.delete(0,'end')
e_accno.delete(0,'end')
e_bankname.delete(0,'end')
e_IFSC.delete(0,'end')
e_creditno.delete(0,'end')
e_debitno.delete(0,'end')
e_tenthmark.delete(0,'end')
e_twenthmark.delete(0,'end')
e_cgpa.delete(0,'end')
MessageBox.showinfo("NEXT","COULDYOUWANTTOCONTINUE");
con.close();
newwindow2.destroy()
return
insert=Button(newwindow2,text="INSERT",bg='#116562',fg='white',width=7,bd=5,com
mand=insert)
insert.place(x=50,y=540)
update3=Button(newwindow2,text="UPDATE",bg='#116562',fg='white',width=7,bd=5,
command=update3)
update3.place(x=150,y=540)
get3=Button(newwindow2,text="GETDATA",bg='#116562',fg='white',width=7,bd=5,co
mmand=get3)
get3.place(x=250,y=540)
nexttwo=Button(newwindow2,text="NEXT",bg='#116562',fg='white',width=7,bd=5,co
mmand=nexttwo)
nexttwo.place(x=350,y=540)
newwindow2.mainloop()
################################################
newwindow3=Tk()
newwindow3.title("personalinformation")
newwindow3.geometry("550x550")
bg=PhotoImage(file="C:/Users/ELCOT/Pictures/Screenshots/IMG_20211021_131459.p
ng")
submit=Label(newwindow3,image=bg)
submit.place(x=0,y=0)
lb1=Label(newwindow3,text="***SKILLS***",font=('white',12,'italic
bold'),borderwidth=4,width=25,relief=GROOVE,bg='#116562')
lb1.pack()
Aadharid=Label(newwindow3,text="AADHARID",bg='#091e42',fg='white')
Aadharid.place(x=30,y=40)
hobby=Label(newwindow3,text="HOBBY",bg='#091e42',fg='white')
hobby.place(x=30,y=80)
sports=Label(newwindow3,text="SPORTS",bg='#091e42',fg='white')
sports.place(x=30,y=120)
lang=Label(newwindow3,text="LANGUAGE-KNOWN",bg='#091e42',fg='white')
lang.place(x=30,y=160)
e_Aadharid=Entry(width=30,bd=5)
e_Aadharid.place(x=200,y=40)
e_hobby=Entry(width=30,bd=5)
e_hobby.place(x=200,y=80)
e_sports=Entry(width=30,bd=5)
e_sports.place(x=200,y=120)
e_lang=Entry(width=30,bd=5)
e_lang.place(x=200,y=160)
defsubmit():
Aadharid=e_Aadharid.get();
hobby=e_hobby.get();
sports=e_sports.get();
lang=e_lang.get();
if(Aadharid==""orhobby==""orsports==""orlang==""):
MessageBox.showinfo("INSERTSTATUS","ALLFIELDSAREREQUIRED")
else:
con=mysql.connect(host="localhost",user="root",password="priya@1992002",database="
PERSONALINFORMATION")
cursor=con.cursor()
cursor.execute("insertintoacti
values('"+Aadharid+"','"+hobby+"','"+sports+"','"+lang+"')")
cursor.execute("commit");
e_Aadharid.delete(0,'end')
e_hobby.delete(0,'end')
e_sports.delete(0,'end')
e_lang.delete(0,'end')
MessageBox.showinfo("INSERTSTATUS","SUBMITTEDSUCCESSFULLY");
con.close();
defupdate4():
Aadharid=e_Aadharid.get()
hobby=e_hobby.get();
sports=e_sports.get();
lang=e_lang.get();
if(Aadharid==""orhobby==""orsports==""orlang==""):
MessageBox.showinfo("UpdateStatus","AllFieldsarerequired")
else:
con=
mysql.connect(host="localhost",user="root",password="priya@1992002",database="PERS
ONALINFORMATION")
cursor=con.cursor()
cursor.execute("updateactisethobby='"+hobby+"',sports='"+sports
+"',lang='"+lang+"'whereAadharid='"+Aadharid+"'")
cursor.execute("commit");
e_Aadharid.delete(0,'end')
e_hobby.delete(0,'end')
e_sports.delete(0,'end')
e_lang.delete(0,'end')
MessageBox.showinfo("UpdateStatus","UpdatedSuccessfully");
con.close();
defget4():
if(e_Aadharid.get()==""):
MessageBox.showinfo("FetchStatus","IDiscompulsaryfordelete")
else:
con=
mysql.connect(host="localhost",user="root",password="priya@1992002",database="PERS
ONALINFORMATION")
cursor=con.cursor()
cursor.execute("select*from actiwhereAadharid='"+e_Aadharid.get()+"'")
rows=cursor.fetchall()
forrowinrows:
e_hobby.insert(0,row[1])
e_sports.insert(0,row[2])
e_lang.insert(0,row[3])
con.close();
update4=Button(newwindow3,text="UPDATE",bg='#116562',fg='white',width=7,bd=5,
command=update4)
update4.place(x=150,y=300)
get4=Button(newwindow3,text="GETDATA",bg='#116562',fg='white',width=7,bd=5,co
mmand=get4)
get4.place(x=220,y=300)
submit=Button(newwindow3,text="SUBMIT",bg='#116562',fg='white',width=7,bd=5,co
mmand=submit)
submit.place(x=300,y=300)
newwindow3.mainloop()
